In [1]:
pip --version

pip 23.2.1 from C:\Users\Admin\anaconda3\Lib\site-packages\pip (python 3.11)

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install camelcase

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for camelcase: filename=camelcase-0.2-py3-none-any.whl size=1779 sha256=f9c53043c52284442276affd764ba6dc92804f731b7620bf2d6ff560f42392c2
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\9b\03\38\e96c3419390e51c6f282e9793e392eb2996b4059eb6739165b
Successfully built camelcase
Note: you may need to restart the kernel to use updated packages.


In [3]:
import camelcase
c = camelcase.CamelCase()

txt = "hello world"

print(c.hump(txt))


Hello World


In [4]:
import numpy
arr=numpy.array([2,8,10,5,9])
print(arr)

[ 2  8 10  5  9]


In [7]:
import numpy as np
arr=np.array([2,8,10,5,9])
print(arr)

[ 2  8 10  5  9]


In [6]:
#checking numpy version
import numpy as np
print(np.__version__)

1.24.3


In [8]:
import numpy as np
arr=np.array([2,8,10,5,9])
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [10]:
#Checking no of dimension-ndim attribute
import numpy as np
arr=np.array(5) 
arr1=np.array([2,8,10,5,9]) 
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr.ndim)
print(arr1.ndim) 
print(arr2.ndim) 
print(arr3.ndim)

0
1
2
3


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [12]:
arr=np.array([2,8,10,5,9])
print(arr)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

[ 2  8 10  5  9]
2
8
10
5
9


In [13]:
arr=np.array([2,8,10,5,9])
print(arr)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])

[ 2  8 10  5  9]
2
8
10
5
9


IndexError: index 5 is out of bounds for axis 0 with size 5

In [14]:
arr=np.array(10)
for(i=0;i<10;i++);
print(arr)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (986978195.py, line 2)

In [15]:
arr=np.array([2,4,5,6,7,8])
for i in arr:
    print i

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (729550332.py, line 3)

In [16]:
arr=np.array([2,4,5,6,7,8])
for i in arr:
    print (i)

2
4
5
6
7
8


In [18]:
arr=[]
n=int(input())
for i in range (n):
    element=input()
    arr.append(element)
print(arr)

5
1
2
3
7
8
['1', '2', '3', '7', '8']


In [19]:
arr=[1,2,3,4,5]
sum=0
for i in range(len(arr)):
    sum+=arr[i]
print(sum)

15


In [23]:
arr=[]
n=int(input())
sum=0
for i in range (n):
    element=int(input())
    arr.append(element)
    sum+=arr[i]
print(sum/n)

3
1
2
3
2.0


In [24]:
arr=[]
n=int(input())
for i in range (n):
    element=input()
    arr.append(element)
print(arr[::-1])

3
1
2
3
['3', '2', '1']


In [25]:
arr=[1,2,3,4,5]
for i in range(-1,-5,-1):
    print(arr[i])

5
4
3
2


In [26]:
arr=[1,2,3,4,5]
for i in range(-1,-6,-1):
    print(arr[i])

5
4
3
2
1


In [27]:
arr=[1,2,3,4,5]
n=len(arr)*-1
for i in range(-1,n-1,-1):
    print(arr[i])

5
4
3
2
1


In [33]:
# find the max value in a array
#find the second maximum element in a array
arr=[1,2,3,4,5]
max=0
for i in range(len(arr)):
    if(max<arr[i]):
        max=arr[i]
a=max
print(a)
max=0
for i in range(len(arr)):
    if(max<arr[i] and arr[i]!=a):
        max=arr[i]
print(max)


5
4


In [34]:
#Accessing 2D Arrays
#To access 2D arrays we need nested loop one is for row and another is for column
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First 1D array:",a[0])
print("Second 1D array:",a[1])
print("Third 1D array:",a[2])

First 1D array: [1 2 3]
Second 1D array: [4 5 6]
Third 1D array: [7 8 9]


In [35]:
print("Accessing row 0 elements:")
print(a[0,0])
print(a[0,1])
print(a[0,2])
print("Accessing row 1 elements:")
print(a[1,0])
print(a[1,1])
print(a[1,2])
print("Accessing row 2 elements:")
print(a[2,0])
print(a[2,1])
print(a[2,2])

Accessing row 0 elements:
1
2
3
Accessing row 1 elements:
4
5
6
Accessing row 2 elements:
7
8
9


In [36]:
print("Accessing column 0 elements:")
print(a[0,0])
print(a[1,0])
print(a[2,0])
print("Accessing column 1 elements:")
print(a[0,1])
print(a[1,1])
print(a[2,1])
print("Accessing column 2 elements:")
print(a[0,2])
print(a[1,2])
print(a[2,2])

Accessing column 0 elements:
1
4
7
Accessing column 1 elements:
2
5
8
Accessing column 2 elements:
3
6
9


In [37]:
print("The given matrix is:")
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i,j],end=' ')
    print()

The given matrix is:
1 2 3 
4 5 6 
7 8 9 


In [38]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [39]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
for i in a:
    for j in i:
        for k in j:
            print(k,end=' ')
        print()

1 2 3 
4 5 6 
7 8 9 
10 11 12 
13 14 15 
16 17 18 


In [40]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:5])

[1 2 3 4 5]


In [41]:
print(a[0:])
print(a[:])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
print(a[-10:-5])
print(a[0::2])

[1 2 3 4 5]
[1 3 5 7 9]


In [43]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [ ]:
Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer b - boolean u - unsigned integer f - float c - complex float m - timedelta M - datetime O - object S - string U - unicode string V - fixed chunk of memory for other type ( void )

In [44]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2.2,4.5,8.9])
c=np.array(['Tushar','Saran','c'])
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
<U6


In [45]:
import numpy as np
a=np.array([1,2,3],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3']
|S1


In [46]:
a=np.array([1,'c',3],dtype='i')

ValueError: invalid literal for int() with base 10: 'c'

In [47]:
#Converting datatypes-astype() method
import numpy as np
a=np.array([1.1,2.2,3.3])
b=a.astype('i')
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1.1 2.2 3.3]
float64
[1 2 3]
int32


In [48]:
a=np.array([1,-2,0])
b=a.astype(bool)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[ 1 -2  0]
int32
[ True  True False]
bool


In [ ]:
Array copy and view

Copy: * Creates a new array * Any changes made to copy will not 
    reflect on original and vice versa View: * Just a view of the original array * Changes made 
        in view will reflect on original

In [49]:
a=np.array([1,-2,0])
b=a.copy()
print("Array a:",a)
print("Array b:",b)


Array a: [ 1 -2  0]
Array b: [ 1 -2  0]


In [52]:
a[0]=6
print("Array a:",a)
print("Array b:",b)
b[0]=9
print("Array a:",a)
print("Array b:",b)

Array a: [ 6 -2  0]
Array b: [ 1 -2  0]
Array a: [ 6 -2  0]
Array b: [ 9 -2  0]


In [54]:
a=np.array([1,-2,0])
b=a.view()
print("Array a:",a)
print("Array b:",b)
a[0]=6
print("Array a:",a)
print("Array b:",b)
b[0]=9
print("Array a:",a)
print("Array b:",b)

Array a: [ 1 -2  0]
Array b: [ 1 -2  0]
Array a: [ 6 -2  0]
Array b: [ 6 -2  0]
Array a: [ 9 -2  0]
Array b: [ 9 -2  0]


In [55]:
#Check if array owns its data-base attribute
a=np.array([1,-2,0])
b=a.copy()
c=a.view()
print(b.base)
print(c.base)
print(a.base)

None
[ 1 -2  0]
None


In [56]:
#Array shape
import numpy as np
a=np.array([1,-2,0])
print(a.shape)


(3,)


In [57]:
#Array shape
import numpy as np
a=np.array([1,-2,0])
print(a.shape)
a=np.array([[1,-2,0],[4,5,6]])
print(a.shape)

(3,)
(2, 3)


In [58]:
#Unknown dimension
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3,-1)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [59]:
#Iteration using nditer()
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(a):
    print(x)
    

1
2
3
4
5
6
7
8
9


In [60]:
a=np.array([1,2,3,4,5])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


In [61]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a[:,::2]):
    print(x)

1
3
5
7


In [62]:
#Enumerated iteration using ndenumerate()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])
for i,x in np.ndenumerate(a):
    print(i,x)
for i,x in np.ndenumerate(b):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [63]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [65]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)
print("First array\n",a)
print("Second array\n",b)
print("Result array\n",c)

First array
 [[1 2]
 [3 4]]
Second array
 [[5 6]
 [7 8]]
Result array
 [[1 2 5 6]
 [3 4 7 8]]


In [66]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
print(c)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b))
print("First array\n",a)
print("Second array\n",b)
print("Result array\n",c)

[1 2 3 4 5 6 7 8]
First array
 [[1 2]
 [3 4]]
Second array
 [[5 6]
 [7 8]]
Result array
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
#Joining arrays using stack function
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack((a,b),axis=1)
print(c)
#stacking along rows
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.hstack((a,b))
c=np.vstack((a,b))
print(c)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [70]:
#Stacking along depth
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [72]:
#Spliting arrays
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [73]:
#searching arrays using where()
# where() returns index and the datatype
import numpy as np
a=np.array([1,2,3,4,5,6,4,7,8,4])
b=np.where(a==4)
print(b)

(array([3, 6, 9], dtype=int64),)


In [74]:
a=np.array([1,2,3,4,5,6,4,7,8,4])
b=np.where(a%2==0)
print(b)

(array([1, 3, 5, 6, 8, 9], dtype=int64),)


In [79]:
#Search sorted
import numpy as np
a=np.array([10,2,3,9,0,1,8,4])# 0 1 2 3 4 8 9 10
b=np.searchsorted(a,7)#2nd argument shows that where 7 should be inserted
print(b)
print(a)

6
[10  2  3  9  0  1  8  4]


In [82]:
b=np.searchsorted(a,1,side='right')
print(b)

6
